@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> InitializeState : StartGame

state InitializeState {
  [*] --> WaitForPlayersState
state WaitForPlayersState{
[*]--> Idle
}
}
Idle --d> ProgrammingState


state ProgrammingState {
  [*] --> NewProgramSelection
  NewProgramSelection --L> Processing : Choose card
  Processing --L> NewProgramSelection: Player wants more cards


}
Processing --> WaitProgrammingState: Finish Programming

state WaitProgrammingState{
[*] --> Idle2
}
Idle2 --> WaitActivationState

state WaitActivationState{
[*] --> Idle3
Idle3 --d> ActivationState:Your turn
}

state ActivationState{
[*] --> Activate

}
Activate --r> Idle3:Not your turn

Activate --> WaitEndTurnState:Cards have been activated

state WaitEndTurnState{
[*] --> EndTurn
}

EndTurn --> PlayerInterractionState

state PlayerInterractionState{
[*] --> Interraction
}
Interraction --u> NewProgramSelection:No Winner Found
Interraction --> [*]: Winner Found



@enduml