@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Player
Participant System

Player -> System: Start program

ALT Create a game
Player -> System: Create board
System --> Player: Ask for amount of players

Player -> System: Enter amount of players for game
else load a game

Player -> System: Loading game


end

System --> Player: Game is initialized
Player -> System: Play/Continue the game

Player -> System: Exit, Save or Finish

@enduml